export const CLINTON_TWEETS_REQUEST = "CLINTON_TWEETS_REQUEST";
export const CLINTON_TWEETS_SUCCESS = "CLINTON_TWEETS_SUCCESS";
export const CLINTON_TWEETS_FAIL = "CLINTON_TWEETS_FAIL";
export const TRUMP_TWEETS_REQUEST = "TRUMP_TWEETS_REQUEST";
export const TRUMP_TWEETS_SUCCESS = "TRUMP_TWEETS_SUCCESS";
export const TRUMP_TWEETS_FAIL = "TRUMP_TWEETS_FAIL";
